CREATE VIEW [dbo].[vw_EquipReportDetails]
AS
SELECT
    (e.unit + ' - ' + e.fDesc) AS [Equipment Name],
    e.state AS State,
    e.cat AS [Service Type],
    e.category AS Category,
    e.manuf AS Manuf,
    e.price AS Price,
    e.last AS [Last Service],
    e.since AS Installed,
    e.Building AS [Building Type],
    e.id AS ID,
    e.unit AS [Name],
    e.type AS [Type],
    e.fdesc AS [Description],
    CASE
        WHEN e.status = 0 THEN 'Active'
        ELSE 'Inactive'
    END AS [Status],
    r.name AS Customer,
    l.id AS [Location ID],
    l.tag AS [Location],
    (l.address + ', ' + l.city + ', ' + l.state + ', ' + l.zip) AS [Address],
	CASE
        WHEN ISNULL(e.shut_down, 0) = 0 THEN 'No'
        ELSE 'Yes'
    END AS [Shutdown],
    e.Classification,
    e.ShutdownReason,
    --l.Loc,e.ID as [Unit Id],
    (SELECT Owner.ID FROM Owner WHERE Owner.ID = e.Owner) AS OwnerID,
	(SELECT Rol.Name FROM Rol WHERE ID = e.Owner AND Rol.Type = 0) AS OwnerName,
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'annual Insp Date')    AS [Annual Insp Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Annual Inspector')    AS [Inspector Name],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Balastrades')    AS Balastrades,
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Building ELBI')    AS [Building ELBI],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Building Power')    AS [Building Power],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Capacity')    AS Capacity,
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Car Station')    AS [Car Station],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Car Station Bulb')    AS [Car Station Bulb],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Car Station Mfg')    AS [Car Station Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Car Weight')    AS [Car Weight],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Code Year')    AS [Code Year],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Coil Part Number')    AS [Coil Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Counterweight Roller Part Number')    AS [Counterweight Roller Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Door Opening Width')    AS [Door Opening Width],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Door Operator')    AS [Door Operator],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Door Operator Belt')    AS [Door Operator Belt],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Door Roller Part Number')    AS [Door Roller Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Door Type')    AS [Door Type],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Due Date')    AS [Due Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Emergency battery charger')    AS [Emergency Battery Charger],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Emergency light battery')    AS [Emergency light battery],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Emergency Light Bulb')    AS [Emergency Light Bulb],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Comb Teeth')    AS [Escalator Comb Teeth],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Handrail')    AS [Escalator Handrail],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Handrail Color')    AS [Escalator Handrail Color],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Handrail Length')    AS [Escalator Handrail Length],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Handrail Replacement Date')    AS [Escalator Handrail Replacement Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Roller Part Number')    AS [Escalator Roller Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Skirt Switch')    AS [Escalator Skirt Switch],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Speed')    AS [Escalator Speed],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Escalator Step Width')    AS [Escalator Step Width],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Fire Service Key')    AS [Fire Service Key],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Fire Service Phase II')    AS [Fire Service Phase II],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Floors')    AS Floors,
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'FPM')    AS FPM,
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Five Year Insp Date')    AS [Five Year Insp Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Gate Switch Part Number')    AS [Gate Switch Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Generator Brush Part Number')    AS [Generator Brush Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Generator Mfg')    AS [Generator Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Gib Part Number')    AS [Gib Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Governor Mfg')    AS [Governor Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Governor Rope Length')    AS [Governor Rope Length],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Governor Rope Size')    AS [Governor Rope Size],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Guide Roller Part Number')    AS [Guide Roller Part Number],
   	(SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Hall Lantern Lens Cap')    AS [Hall Lantern Lens Cap],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Hall Lantern Mfg')    AS [Hall Lantern Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Hall Station bulb')    AS [Hall Station bulb],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Hall Station Manufacturer')    AS [Hall Station Manufacturer],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Hoistway Access Switch')    AS [Hoistway Access Switch],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Input Board')    AS [Input Board],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Interlock Part Number')    AS [Interlock Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Mfg Job Number')    AS [Mfg Job Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Model Type')    AS [Model Type],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Motor RPM')    AS [Motor RPM],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Motor Type')    AS [Motor Type],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Oil Line Size')    AS [Oil Line Size],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Openings')    AS [Openings],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Output Board')    AS [Output Board],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Packing Number')    AS [Packing Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Piston Diameter')    AS [Piston Diameter],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Position Indicator Bulb')    AS [Position Indicator Bulb],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Pump Motor Mfg')    AS [Pump Motor Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Pump Unit Mfg')    AS [Pump Unit Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Pump Motor Belt')    AS [Pump Motor Belt],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'purchase Date')    AS [purchase Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Altered Date')    AS [Altered Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Rope Length')    AS [Rope Length],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Rope Size')    AS [Rope Size],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'refNo')    AS [Ref No],
	(SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Safety Edges')    AS [Safety Edges],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Serial No.')    AS [Serial No.],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Service Interval')    AS [Service Interval],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Service Interval Unit')    AS [Service Interval Unit],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Spirator Part Number')    AS [Spirator Part Number],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Start Type')    AS [Start Type],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Starter Contact Mfg and Part No')    AS [Starter Contact Mfg and Part No],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Time Clock')    AS [Time Clock],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Time Clock Model')    AS [Time Clock Model],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'TXE')    AS [TXE],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Valve Mfg')    AS [Valve Mfg],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'warrantyExpirationDate')    AS [Warranty Expiration Date],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'wherePurchased')    AS [Where Purchased],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Annual Inspection Violations')    AS [Annual Inspection Violations],
    (SELECT        value    FROM ElevTItem    WHERE Elev = e.ID    AND fdesc = 'Annual Inspector-Customer Preference')    AS [Annual Inspector-Customer Preference]

FROM elev e
INNER JOIN loc l    ON l.Loc = e.Loc
INNER JOIN owner o    ON o.id = l.owner
INNER JOIN rol r    ON o.rol = r.id
WHERE e.id IS NOT NULL


GO