CREATE TABLE [dbo].[BRCompany](
	[ID] [int] NOT NULL,
	[Name] [varchar](75) NULL,
	[Manager] [varchar](50) NULL,
	[Address] [varchar](100) NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](2) NULL,
	[Zip] [varchar](10) NULL,
	[Phone] [varchar](25) NULL,
	[Fax] [varchar](25) NULL,
	[CostCenter] [varchar](20) NULL,
	[InvRemarks] [varchar](1000) NULL,
	[Logo] [image] NULL,
	[LogoPath] [varchar](255) NULL,
	[BillRemit] [varchar](1000) NULL,
	[PORemit] [varchar](1000) NULL,
	[LocDTerr] [varchar](50) NULL,
	[LocDRoute] [varchar](50) NULL,
	[LocDZone] [varchar](50) NULL,
	[LocDStax] [varchar](50) NULL,
	[LocType] [varchar](50) NULL,
	[ARTerms] [varchar](50) NULL,
	[ChargeInt] [varchar](50) NULL,
	[ADP] [varchar](3) NULL,
	[CB] [numeric](30, 4) NULL,
	[ARContact] [varchar](75) NULL,
	[OType] [varchar](50) NULL,
	[DArea] [varchar](3) NULL,
	[DState] [varchar](2) NULL,
	[MileRate] [numeric](30, 4) NULL,
	[PriceD1] [numeric](30, 4) NULL,
	[PriceD2] [numeric](30, 4) NULL,
	[PriceD3] [numeric](30, 4) NULL,
	[PriceD4] [numeric](30, 4) NULL,
	[PriceD5] [numeric](30, 4) NULL,
	[UTaxR] [tinyint] NULL,
	[UTax] [varchar](25) NULL,
	[Company] [varchar](50) NULL,
	[Status] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
