
CREATE TABLE [dbo].[EmailDetails](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EmailID] [int] NULL,
	[Fields] [varchar](50) NULL,
 CONSTRAINT [PK_EmailDetails] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
