CREATE TABLE [dbo].[Emp] (
    [ID]                INT             IDENTITY (1, 1) NOT NULL,
    [fFirst]            VARCHAR (15)    NULL,
    [Last]              VARCHAR (25)    NULL,
    [Middle]            VARCHAR (15)    NULL,
    [Name]              VARCHAR (55)    NULL,
    [Rol]               INT             NULL,
    [SSN]               VARCHAR (11)    NULL,
    [Title]             VARCHAR (50)    NULL,
    [Sales]             SMALLINT        NOT NULL,
    [Field]             SMALLINT        NOT NULL,
    [Status]            SMALLINT        NULL,
    [Pager]             VARCHAR (100)   NULL,
    [InUse]             SMALLINT        NOT NULL,
    [PayPeriod]         SMALLINT        NULL,
    [DHired]            DATETIME        NULL,
    [DFired]            DATETIME        NULL,
    [DBirth]            DATETIME        NULL,
    [DReview]           DATETIME        NULL,
    [DLast]             DATETIME        NULL,
    [FStatus]           SMALLINT        NULL,
    [FAllow]            SMALLINT        NULL,
    [FAdd]              NUMERIC (30, 2) NULL,
    [SStatus]           SMALLINT        NULL,
    [SAllow]            SMALLINT        NULL,
    [SAdd]              NUMERIC (30, 2) NULL,
    [CallSign]          VARCHAR (50)    NULL,
    [VRate]             NUMERIC (30, 4) NULL,
    [VBase]             SMALLINT        NULL,
    [VLast]             NUMERIC (30, 2) NULL,
    [VThis]             NUMERIC (30, 2) NULL,
    [Sick]              NUMERIC (30, 2) NULL,
    [PMethod]           SMALLINT        NULL,
    [PFixed]            SMALLINT        NULL,
    [PHour]             NUMERIC (30, 2) NULL,
    [LName]             SMALLINT        NULL,
    [LStatus]           SMALLINT        NULL,
    [LAllow]            SMALLINT        NULL,
    [PRTaxE]            INT             NULL,
    [State]             VARCHAR (2)     NULL,
    [Salary]            NUMERIC (30, 2) NULL,
    [SalaryF]           SMALLINT        NULL,
    [SalaryGL]          INT             NULL,
    [fWork]             INT             NULL,
    [NPaid]             SMALLINT        NULL,
    [Balance]           NUMERIC (30, 2) NULL,
    [PBRate]            NUMERIC (30, 2) NULL,
    [FITYTD]            NUMERIC (30, 2) NULL,
    [FICAYTD]           NUMERIC (30, 2) NULL,
    [MEDIYTD]           NUMERIC (30, 2) NULL,
    [FUTAYTD]           NUMERIC (30, 2) NULL,
    [SITYTD]            NUMERIC (30, 2) NULL,
    [LocalYTD]          NUMERIC (30, 2) NULL,
    [BonusYTD]          NUMERIC (30, 2) NULL,
    [HolH]              NUMERIC (30, 2) NULL,
    [HolYTD]            NUMERIC (30, 2) NULL,
    [VacH]              NUMERIC (30, 2) NULL,
    [VacYTD]            NUMERIC (30, 2) NULL,
    [ZoneH]             NUMERIC (30, 2) NULL,
    [ZoneYTD]           NUMERIC (30, 2) NULL,
    [ReimbYTD]          NUMERIC (30, 2) NULL,
    [MileH]             NUMERIC (30, 2) NULL,
    [MileYTD]           NUMERIC (30, 2) NULL,
    [Race]              VARCHAR (40)    NULL,
    [Sex]               VARCHAR (10)    NULL,
    [Ref]               VARCHAR (15)    NULL,
    [ACH]               SMALLINT        NULL,
    [ACHType]           SMALLINT        NULL,
    [ACHRoute]          VARCHAR (20)    NULL,
    [ACHBank]           VARCHAR (20)    NULL,
    [Anniversary]       DATETIME        NULL,
    [Level]             INT             NULL,
    [WageCat]           INT             NULL,
    [DSenior]           DATETIME        NULL,
    [PRWBR]             INT             NULL,
    [PDASerialNumber_1] VARCHAR (100)   NULL,
    [StatusChange]      TINYINT         NULL,
    [SCDate]            DATETIME        NULL,
    [SCReason]          VARCHAR (2)     NULL,
    [DemoChange]        TINYINT         NULL,
    [Language]          VARCHAR (2)     NULL,
    [TicketD]           TINYINT         NULL,
    [Custom1]           VARCHAR (50)    NULL,
    [Custom2]           VARCHAR (50)    NULL,
    [Custom3]           VARCHAR (50)    NULL,
    [Custom4]           VARCHAR (50)    NULL,
    [Custom5]           VARCHAR (50)    NULL,
    [DDType]            TINYINT         NULL,
    [DDRate]            NUMERIC (30, 4) NULL,
    [ACHType2]          TINYINT         NULL,
    [ACHRoute2]         VARCHAR (20)    NULL,
    [ACHBank2]          VARCHAR (20)    NULL,
    [BillRate]          NUMERIC (30, 4) NULL,
    [BMSales]           NUMERIC (30, 4) NULL,
    [BMInvAve]          NUMERIC (30, 4) NULL,
    [BMClosing]         NUMERIC (30, 4) NULL,
    [BMBillEff]         NUMERIC (30, 4) NULL,
    [BMProdEff]         NUMERIC (30, 4) NULL,
    [BMAveTask]         INT             NULL,
    [BMCustom1]         INT             NULL,
    [BMCustom2]         INT             NULL,
    [BMCustom3]         INT             NULL,
    [BMCustom4]         INT             NULL,
    [BMCustom5]         INT             NULL,
    [TaxCodeNR]         VARCHAR (10)    NULL,
    [TaxCodeR]          VARCHAR (10)    NULL,
    [DeviceID]          VARCHAR (100)   NULL,
    [MileageRate]       NUMERIC (30, 2) NULL,
    [Import1]           VARCHAR (100)   NULL, 
    [MSDeviceId] NCHAR(100) NULL, 
    [PayPortalPassword] [varchar](30) NULL,
	[SickRate] [numeric](30, 4) NULL,
	[SickAccrued] [numeric](30, 2) NULL,
	[SickUsed] [numeric](30, 2) NULL,
	[SickYTD] [numeric](30, 2) NULL,
	[VacAccrued] [numeric](30, 2) NULL,
    [SCounty] [int] NULL,
    PDASerialNumber [varchar](50) NULL,
    [TechnicianBio] Image NULL,
    CONSTRAINT [PK_Emp] PRIMARY KEY ([ID])
);

