
CREATE TABLE [dbo].[Inv](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](30) NULL,
	[fDesc] [varchar](8000) NULL,
	[Part] [varchar](50) NULL,
	[Status] [smallint] NULL,
	[SAcct] [int] NULL,
	[Measure] [varchar](10) NULL,
	[Tax] [smallint] NOT NULL,
	[Balance] [numeric](30, 2) NULL,
	[Price1] [numeric](30, 4) NULL,
	[Price2] [numeric](30, 4) NULL,
	[Price3] [numeric](30, 4) NULL,
	[Price4] [numeric](30, 4) NULL,
	[Price5] [numeric](30, 4) NULL,
	[Remarks] [varchar](8000) NULL,
	[Cat] [smallint] NULL,
	[LVendor] [int] NULL,
	[LCost] [numeric](30, 4) NULL,
	[AllowZero] [smallint] NOT NULL,
	[Type] [smallint] NULL,
	[InUse] [smallint] NOT NULL,
	[EN] [int] NULL,
	[Hand] [numeric](30, 2) NULL,
	[Aisle] [varchar](15) NULL,
	[fOrder] [numeric](30, 2) NULL,
	[Min] [numeric](30, 2) NULL,
	[Shelf] [varchar](15) NULL,
	[Bin] [varchar](15) NULL,
	[Requ] [numeric](30, 2) NULL,
	[Warehouse] [varchar](5) NULL,
	[Price6] [numeric](30, 4) NULL,
	[Committed] [numeric](30, 4) NULL,
	[QBInvID] [varchar](100) NULL,
	[LastUpdateDate] [datetime] NULL,
	[QBAccountID] [varchar](100) NULL,
	[Available] [numeric](30, 4) NULL,
	[IssuedOpenJobs] [numeric](30, 4) NULL,
	[Description2] [varchar](255) NULL,
	[Description3] [varchar](255) NULL,
	[Description4] [varchar](255) NULL,
	[DateCreated] [datetime] NULL,
	[Class] [varchar](100) NULL,
	[Specification] [varchar](255) NULL,
	[Specification2] [varchar](255) NULL,
	[Specification3] [varchar](255) NULL,
	[Specification4] [varchar](255) NULL,
	[Revision] [varchar](255) NULL,
	[LastRevisionDate] [datetime] NULL,
	[Drawing] [varchar](255) NULL,
	[Reference] [varchar](255) NULL,
	[Length] [varchar](255) NULL,
	[Width] [varchar](255) NULL,
	[Weight] [varchar](255) NULL,
	[InspectionRequired] [bit] NULL DEFAULT ((0)),
	[CoCRequired] [bit] NULL DEFAULT ((0)),
	[ShelfLife] [numeric](30, 4) NULL,
	[SerializationRequired] [bit] NULL DEFAULT ((0)),
	[GLcogs] [varchar](100) NULL,
	[GLPurchases] [varchar](100) NULL,
	[ABCClass] [varchar](100) NULL,
	[OHValue] [numeric](30, 4) NULL,
	[OOValue] [numeric](30, 4) NULL,
	[OverIssueAllowance] [bit] NULL DEFAULT ((0)),
	[UnderIssueAllowance] [bit] NULL DEFAULT ((0)),
	[InventoryTurns] [numeric](30, 4) NULL,
	[MOQ] [numeric](30, 4) NULL,
	[MinInvQty] [numeric](30, 4) NULL,
	[MaxInvQty] [numeric](30, 4) NULL,
	[Commodity] [varchar](100) NULL,
	[LastReceiptDate] [datetime] NULL,
	[MPN] [varchar](100) NULL,
	[ApprovedManufacturer] [varchar](100) NULL,
	[ApprovedVendor] [varchar](100) NULL,
	[EAU] [decimal](30, 4) NULL,
	[EOLDate] [datetime] NULL,
	[WarrantyPeriod] [int] NULL,
	[PODueDate] [datetime] NULL,
	[DefaultReceivingLocation] [bit] NULL DEFAULT ((0)),
	[DefaultInspectionLocation] [bit] NULL DEFAULT ((0)),
	[LastSalePrice] [numeric](30, 4) NULL,
	[AnnualSalesQty] [numeric](30, 4) NULL,
	[AnnualSalesAmt] [numeric](30, 4) NULL,
	[QtyAllocatedToSO] [numeric](30, 4) NULL,
	[MaxDiscountPercentage] [numeric](30, 4) NULL,
	[Height] [varchar](255) NULL,
	[EOQ] [numeric](30, 4) NULL,
	[UnitCost] [numeric](30, 4) NULL,
	[GLSales] [int] NULL,
	[LeadTime] [int] NULL,
	[Eco] [varchar](100) NULL,
	[DateLastPurchase] [datetime] NULL, 
    [WarehouseCount] INT NULL, 
    CONSTRAINT [PK_Inv] PRIMARY KEY ([ID])
)
;

