CREATE TABLE [dbo].[Labels](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[Screen] [varchar](25) NULL,
	[Name] [varchar](25) NULL,
	[Label] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]