CREATE TABLE [dbo].[Lead] (
    [ID]             INT             NOT NULL,
    [fDesc]          VARCHAR (255)    NULL,
    [RolType]        SMALLINT        NULL,
    [Rol]            INT             NULL,
    [Type]           VARCHAR (15)    NULL,
    [Address]        VARCHAR (250)   NULL,
    [City]           VARCHAR (50)    NULL,
    [State]          VARCHAR (2)     NULL,
    [Zip]            VARCHAR (10)    NULL,
    [Owner]          INT             NULL,
    [Status]         SMALLINT        NULL,
    [Probability]    SMALLINT        NULL,
    [Level]          SMALLINT        NULL,
    [Revenue]        NUMERIC (30, 2) NULL,
    [Cost]           NUMERIC (30, 2) NULL,
    [Labor]          NUMERIC (30, 2) NULL,
    [Profit]         NUMERIC (30, 2) NULL,
    [Ratio]          NUMERIC (30, 2) NULL,
    [Remarks]        VARCHAR (8000)  NULL,
    [Latt]           INT             NULL,
    [fLong]          INT             NULL,
    [GeoLock]        SMALLINT        NOT NULL,
    [Country]        VARCHAR (50)    NULL,
    [CloseDate]      DATETIME        NULL,
    [NextStep]       VARCHAR (50)    NULL,
    [Desc]           VARCHAR (MAX)   NULL,
    [Source]         VARCHAR (70)    NULL,
    [fuser]          VARCHAR (50)    NULL,
	[AssignedToID]	 INT			 NULL,
    [CreatedBy]      VARCHAR (50)    NULL,
    [CreateDate]     DATETIME        NULL,
    [LastUpdatedBy]  VARCHAR (50)    NULL,
    [LastUpdateDate] DATETIME        NULL,
    [Closed]         SMALLINT        NULL,
    [TicketID]       INT             NULL, 
    [Estimate]		 INT			 NULL,
	[BusinessType]   VARCHAR(50)     NULL,
	[Product]        VARCHAR(50)     NULL,
	[EstimateID] [int] NULL,
	[OpportunityStageID] [int] NULL,
	[CompanyName] [varchar](75) NULL,
	[IsSendMailToSalesPer]  bit null,
	[Department] INT NULL
);

