CREATE TABLE [dbo].[LoadTestItem](
	[LID] [int] NOT NULL,
	[ID] [int] NULL,
	[Loc] [int] NULL,
	[Elev] [int] NULL,
	[Last] [datetime] NULL,
	[Next] [datetime] NULL,
	[Status] [smallint] NULL,
	[Ticket] [int] NULL,
	[Remarks] [ntext] NULL,
	[LastDue] [smalldatetime] NULL,
	[idRolCustomContact] [int] NOT NULL CONSTRAINT [DF_LoadTestItem_idRolCustomContact]  DEFAULT ((0)),
	[Custom1] [varchar](50) NULL,
	[Custom2] [varchar](50) NULL,
	[Custom3] [varchar](50) NULL,
	[Custom4] [varchar](50) NULL,
	[Custom5] [varchar](50) NULL,
	[Custom6] [varchar](50) NULL,
	[Custom7] [varchar](50) NULL,
	[Custom8] [varchar](50) NULL,
	[Custom9] [varchar](50) NULL,
	[Custom10] [varchar](50) NULL,
	[JobId] [int] NULL, 
    [Amount] NUMERIC(32, 2) NULL, 
    [OverrideAmount] NUMERIC(32, 2) NULL, 
    [ThirdPartyName] VARCHAR(50) NULL, 
    [ThirdPartyPhone] VARCHAR(50) NULL,	
	[TestDueBy] [tinyint]  NULL,
	[Chargeable] SMALLINT NULL, 
    [ThirdParty] SMALLINT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]