CREATE TABLE [dbo].[LType] (
    [Type]        VARCHAR (15)    NOT NULL,
    [fDesc]       VARCHAR (50)    NULL,
    [MatCharge]   SMALLINT        NOT NULL,
    [Reg]         INT             NULL,
    [OT]          INT             NULL,
    [DT]          INT             NULL,
    [WReg]        INT             NULL,
    [WOT]         INT             NULL,
    [WDT]         INT             NULL,
    [WCharge]     NUMERIC (30, 2) NULL,
    [HReg]        INT             NULL,
    [HOT]         INT             NULL,
    [HDT]         INT             NULL,
    [HCharge]     NUMERIC (30, 2) NULL,
    [Count]       INT             NULL,
    [Remarks]     VARCHAR (8000)  NULL,
    [Serv]        INT             NULL,
    [LTest]       SMALLINT        NULL,
    [NT]          INT             NULL,
    [Travel]      SMALLINT        NULL,
    [fOver]       SMALLINT        NULL,
    [WNT]         INT             NULL,
    [HNT]         INT             NULL,
    [NonContract] SMALLINT        NULL,
    [Free]        SMALLINT        NOT NULL,
    [FGL]         INT             NULL,
    [EN]          INT             NULL,
    [InvID]       INT             NULL, 
    [Status]      SMALLINT        NULL, -- 0 or Null --> Active, 1 --> Inactive
	[ExpenseGL]   INT             NULL,
    [InterestGL]  INT             NULL,
    [LaborWageC]  INT             NULL, 
	[Route]       VARCHAR (1000)  NULL,
	[LocType]     VARCHAR (100)   NULL,
    Department    nvarchar(1000)  NULL
);

