CREATE TABLE [dbo].[ProjectWIPDetail](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WIPID] [int] NULL,
	[Job] [int] NULL,
	[Type] [nvarchar](50) NULL,
	[Department] [int] NULL,
	[fDesc] [nvarchar](75) NULL,
	[Tag] [nvarchar](100) NULL,
	[Status] [nvarchar](50) NULL,
	[ContractPrice] [numeric](30, 2) NULL,
	[ConstModAdjmts] [numeric](30, 2) NULL,
	[AccountingAdjmts] [numeric](30, 2) NULL,
	[TotalBudgetedExpense] [numeric](30, 2) NULL,
	[TotalEstimatedCost] [numeric](30, 2) NULL,
	[EstimatedProfit] [numeric](30, 2) NULL,
	[ContractCosts] [numeric](30, 2) NULL,
	[CostToComplete] [numeric](30, 2) NULL,
	[PercentageComplete] [numeric](30, 2) NULL,
	[RevenuesEarned] [numeric](30, 2) NULL,
	[GrossProfit] [numeric](30, 2) NULL,
	[BilledToDate] [numeric](30, 2) NULL,
	[ToBeBilled] [numeric](30, 2) NULL,
	[OpenARAmount] [numeric](30, 2) NULL,
	[RetainageBilling] [numeric](30, 2) NULL,
	[IsUpdateRetainage] [bit] DEFAULT(0) NULL,
	[TotalBilling] [numeric](30, 2) NULL,
	[Billings] [numeric](30, 2) NULL,
	[Earnings] [numeric](30, 2) NULL,
	[NPer] [numeric](12, 6) NULL,
	[NPerLastMonth] [numeric](12, 6) NULL,
	[NPerLastYear] [numeric](12, 6) NULL,
	[NPerLastMonthYear] [numeric](12, 6) NULL,
	[Variance] [numeric](30, 2) NULL,
	[Original] [numeric](30, 2) NULL,
	[BillingContract] [numeric](30, 2) NULL,
	[JobBorrow] [numeric](30, 2) NULL,
	[fDate] [datetime] NULL,
	[CloseDate] [datetime] NULL,
 CONSTRAINT [PK_ProjectWIPDetail] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]