CREATE TABLE [dbo].[Prospect] (
    [ID]             INT           NOT NULL,
    [Rol]            INT           NULL,
    [Type]           VARCHAR (20)  NULL,
    [Level]          SMALLINT      NULL,
    [Status]         SMALLINT      NULL,
    [LDate]          DATETIME      NULL,
    [LTime]          DATETIME      NULL,
    [Source]         VARCHAR (50)  NULL,
    [Program]        SMALLINT      NULL,
    [NDate]          DATETIME      NULL,
    [PriceL]         SMALLINT      NULL,
    [Custom1]        VARCHAR (50)  NULL,
    [Custom2]        VARCHAR (50)  NULL,
    [Custom3]        VARCHAR (50)  NULL,
    [Custom4]        VARCHAR (50)  NULL,
    [Custom5]        VARCHAR (50)  NULL,
    [Terr]           INT           NULL,
    [CustomerName]   VARCHAR (50)  NULL,
    [Address]        VARCHAR (250) NULL,
    [City]           VARCHAR (50)  NULL,
    [State]          CHAR (2)      NULL,
    [Zip]            VARCHAR (25)  NULL,
    [Phone]          VARCHAR (25)  NULL,
    [CreatedBy]      VARCHAR (50)  NULL,
    [CreateDate]     DATETIME      NULL,
    [LastUpdatedBy]  VARCHAR (50)  NULL,
    [LastUpdateDate] DATETIME      NULL, 
    [Country] VARCHAR(50) NULL, 
    [BillCountry] VARCHAR(50) NULL, 
    [Referral] VARCHAR(50) NULL, 
	[ReferralType] [varchar](50) NULL,
    [BusinessType] VARCHAR(50) NULL, 
    [STax] VARCHAR(25) NULL 
);

