CREATE TABLE [dbo].[PRRegWItem](
	[CheckID] [int] NULL,
	[PRWID] [int] NULL,
	[Quan] [numeric](30, 2) NULL,
	[Rate] [numeric](30, 2) NULL,
	[Amount] [numeric](30, 2) NULL,
	[YQuan] [numeric](30, 2) NULL,
	[YAmount] [numeric](30, 2) NULL,
	[OQuan] [numeric](30, 2) NULL,
	[ORate] [numeric](30, 2) NULL,
	[OAmount] [numeric](30, 2) NULL,
	[OYQuan] [numeric](30, 2) NULL,
	[OYAmount] [numeric](30, 2) NULL,
	[DQuan] [numeric](30, 2) NULL,
	[DRate] [numeric](30, 2) NULL,
	[DAmount] [numeric](30, 2) NULL,
	[DYQuan] [numeric](30, 2) NULL,
	[DYAmount] [numeric](30, 2) NULL,
	[TQuan] [numeric](30, 2) NULL,
	[TRate] [numeric](30, 2) NULL,
	[TAmount] [numeric](30, 2) NULL,
	[TYQuan] [numeric](30, 2) NULL,
	[TYAmount] [numeric](30, 2) NULL,
	[NQuan] [numeric](30, 2) NULL,
	[NRate] [numeric](30, 2) NULL,
	[NAmount] [numeric](30, 2) NULL,
	[NYQuan] [numeric](30, 2) NULL,
	[NYAmount] [numeric](30, 2) NULL
) ON [PRIMARY]

