CREATE TABLE [dbo].[tblJobCodeDesc_ByJobType](
	[PK] [int] IDENTITY(1,1) NOT NULL,
	[JobTypeID] [int] NOT NULL,
	[JobCodeID] [int] NOT NULL,
	[JobCodeDesc] [nvarchar](100) NULL,
 CONSTRAINT [PK_tblJobCodeDesc_ByJobType] PRIMARY KEY CLUSTERED 
(
	[PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
