CREATE TABLE [dbo].[tblUser] (
    [fUser]                   VARCHAR (50)    NULL,
    [Password]                VARCHAR (50)    NULL,
    [Status]                  SMALLINT        NULL,
    [Access]                  INT             NULL,
    [fStart]                  DATETIME        NULL,
    [fEnd]                    DATETIME        NULL,
    [Since]                   DATETIME        NULL,
    [Last]                    DATETIME        NULL,
    [Remarks]                 VARCHAR (8000)  NULL,
    [Owner]                   VARCHAR (6)     NULL,
    [Location]                VARCHAR (6)     CONSTRAINT [DF_tblUser_Location] DEFAULT ('YYYYYY') NULL,
    [Elevator]                VARCHAR (6)     NULL,
    [Invoice]                 VARCHAR (6)     NULL,
    [Deposit]                 VARCHAR (6)     NULL,
    [Apply]                   VARCHAR (6)     NULL,
    [WriteOff]                VARCHAR (6)     NULL,
    [ProcessC]                VARCHAR (6)     NULL,
    [ProcessT]                VARCHAR (6)     NULL,
    [Interest]                VARCHAR (6)     NULL,
    [Collection]              VARCHAR (6)     NULL,
    [ARViewer]                VARCHAR (6)     NULL,
    [AROther]                 VARCHAR (6)     NULL,
    [Vendor]                  VARCHAR (6)     NULL,
    [Bill]                    VARCHAR (6)     NULL,
    [BillSelect]              VARCHAR (6)     NULL,
    [BillPay]                 VARCHAR (6)     NULL,
    [PO]                      VARCHAR (6)     CONSTRAINT [DF_tblUser_PO] DEFAULT ('YYYYYY') NULL,
    [APViewer]                VARCHAR (6)     NULL,
    [APOther]                 VARCHAR (6)     NULL,
    [Chart]                   VARCHAR (6)     NULL,
    [GLAdj]                   VARCHAR (6)     NULL,
    [GLViewer]                VARCHAR (6)     NULL,
    [IReg]                    VARCHAR (6)     NULL,
    [CReceipt]                VARCHAR (6)     NULL,
    [PJournal]                VARCHAR (6)     NULL,
    [YE]                      VARCHAR (6)     NULL,
    [Service]                 VARCHAR (6)     NULL,
    [Financial]               VARCHAR (6)     NULL,
    [Item]                    VARCHAR (6)     NULL,
    [InvViewer]               VARCHAR (6)     NULL,
    [InvAdj]                  VARCHAR (6)     NULL,
    [Job]                     VARCHAR (6)     NULL,
    [JobViewer]               VARCHAR (6)     NULL,
    [JobTemplate]             VARCHAR (6)     NULL,
    [JobClose]                VARCHAR (6)     NULL,
    [JobResult]               VARCHAR (6)     NULL,
    [Dispatch]                VARCHAR (6)     CONSTRAINT [DF_tblUser_Dispatch] DEFAULT ('YYYYYY') NULL,
    [Ticket]                  VARCHAR (6)     NULL,
    [Resolve]                 VARCHAR (6)     NULL,
    [TestDate]                VARCHAR (6)     NULL,
    [TC]                      VARCHAR (6)     NULL,
    [Human]                   VARCHAR (6)     NULL,
    [DispReport]              VARCHAR (6)     NULL,
    [Violation]               VARCHAR (6)     NULL,
    [UserS]                   VARCHAR (6)     NULL,
    [Control]                 VARCHAR (6)     NULL,
    [Bank]                    VARCHAR (6)     NULL,
    [BankRec]                 VARCHAR (6)     NULL,
    [BankViewer]              VARCHAR (6)     NULL,
    [Manual]                  VARCHAR (6)     NULL,
    [Log]                     VARCHAR (6)     NULL,
    [Code]                    VARCHAR (6)     NULL,
    [STax]                    VARCHAR (6)     NULL,
    [Zone]                    VARCHAR (6)     NULL,
    [Territory]               VARCHAR (6)     NULL,
    [Commodity]               VARCHAR (6)     NULL,
    [Employee]                VARCHAR (6)     NULL,
    [Crew]                    VARCHAR (6)     NULL,
    [PRProcess]               VARCHAR (6)     NULL,
    [PRRemit]                 VARCHAR (6)     NULL,
    [PRRegister]              VARCHAR (6)     NULL,
    [PRReport]                VARCHAR (6)     NULL,
    [Diary]                   VARCHAR (6)     NULL,
    [TTD]                     VARCHAR (6)     NULL,
    [Document]                VARCHAR (6)     NULL,
    [Phone]                   VARCHAR (6)     NULL,
    [ToDo]                    SMALLINT        NULL,
    [Sales]                   VARCHAR (6)     NULL,
    [ToDoC]                   SMALLINT        NULL,
    [EN]                      INT             NULL,
    [Proposal]                VARCHAR (6)     NULL,
    [Convert]                 VARCHAR (6)     NULL,
    [POLimit]                 NUMERIC (30, 2) NULL,
    [FU]                      VARCHAR (6)     NULL,
    [POApprove]               SMALLINT        NULL,
	[POApproveAmt]			  SMALLINT        NULL,
    [Tool]                    VARCHAR (6)     NULL,
    [Vehicle]                 VARCHAR (6)     NULL,
    [Estimates]               VARCHAR (6)     NULL,
    [AwardEstimates]          VARCHAR (6)     NULL,
    [BidResults]              VARCHAR (6)     NULL,
    [Competitors]             VARCHAR (6)     NULL,
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [JobHours]                VARCHAR (6)     NULL,
    [Totals]                  TINYINT         NULL,
    [fDate]                   DATETIME        NULL,
    [PDA]                     TINYINT         NULL,
    [Tech]                    TINYINT         NULL,
    [MassResolvePDATickets]   BIT             NOT NULL,
    [ListsAdmin]              BIT             NOT NULL,
    [UserType]                VARCHAR (20)    NULL,
    [Lang]                    VARCHAR (25)    NULL,
    [MerchantInfoID]          INT             NULL,
    [QBEmployeeID]            VARCHAR (100)   NULL,
    [LastUpdateDate]          DATETIME        NULL,
    [DefaultWorker]           SMALLINT        NULL,
    [massreview]              SMALLINT        NULL,
    [MSMUser]                 VARCHAR (50)    NULL,
    [MSMPass]                 VARCHAR (50)    NULL,
    [EmailAccount]            SMALLINT        NULL,
    [CustomerPayment]         VARCHAR (6)     NULL,
    [MSMEditWarehouse]        SMALLINT        NULL,
    [MSMDeclineTicket]        SMALLINT        NULL,
    [MSAddContact]            SMALLINT        NULL,
    [MSEditContact]           SMALLINT        NULL,
    [MSViewContact]           SMALLINT        NULL,
    [MSEditDispatch]          SMALLINT        NULL,
    [MSUserToken]             VARCHAR (200)   DEFAULT ('') NULL,
    [MSUserDateToken]         VARCHAR (200)   DEFAULT ('') NULL,
    [MOMUserToken]            VARCHAR (200)   DEFAULT ('') NULL,
    [MOMUserDateToken]        VARCHAR (200)   DEFAULT ('') NULL,
    [isMSUser]                TINYINT         NULL,
    [MSUserDate]              DATE            NULL,
    [MSUserSubscriptionType]  TINYINT         NULL,
    [isMOMUser]               TINYINT         NULL,
    [MOMUserDate]             DATE            NULL,
    [MOMUserSubscriptionType] TINYINT         NULL,
    [MSUnassignedTicket]      SMALLINT        NULL,
    [fmsimportdate]           DATETIME        NULL,
    [fmseempid]               VARCHAR (50)    NULL,
    [MSAuthorisedDeviceOnly]  INT             DEFAULT ((0)) NULL,
    [ProjectListPermission]   NCHAR (1)       NULL,
    [FinancePermission]       NCHAR (1)       NULL,
    [BOMPermission]           NCHAR (4)       NULL,
    [WIPPermission]           NCHAR (6)       NULL,
    [Warehouse]               VARCHAR (6)     NULL,
    [InvSetup]                VARCHAR (6)     NULL,
    [MilestonesPermission]    NCHAR (4)       NULL,
    [DocumentPermission]      NCHAR (4)       NULL,
    [ContactPermission]       NCHAR (4)       NULL,
    [SalesAssigned]           BIT             NULL,
    [ProjecttempPermission]   NCHAR (4)       NULL,
	[NotificationOnAddOpportunity]  bit null,
	[MinAmount] [decimal](18, 2) NULL,
	[MaxAmount] [decimal](18, 2) NULL, 
    [ProfileImage] NVARCHAR(MAX) NULL, 
    [CoverImage] NVARCHAR(MAX) NULL, 
    [Lat] NVARCHAR(100) NULL, 
    [Lng] NVARCHAR(100) NULL, 
    [Country] NVARCHAR(50) NULL, 
    [Title] NVARCHAR(100) NULL,
	[BillingCodesPermission]       VARCHAR (4)     NULL,
    [PurchasingmodulePermission]   CHAR (1)        NULL,
    [BillingmodulePermission]      CHAR (1)        NULL, 
    [CODt] DATETIME NULL, 
    [RPO] VARCHAR(6) NULL, 
    [AccountPayablemodulePermission] CHAR (1) NULL,
	[PaymentHistoryPermission] CHAR (4) NULL, 
    [CustomermodulePermission] CHAR NULL, 
    [FinancialmodulePermission] CHAR NULL, 
    [ProcessRCPermission] VARCHAR(6) NULL, 
    [RCmodulePermission] CHAR NULL, 
    [RCRenewEscalatePermission] VARCHAR(4) NULL,
	[RCSafteyTest] VARCHAR(6) NULL,
    [SchedulemodulePermission] CHAR(1) NULL,
    [MTimesheet] VARCHAR(6) NULL,
    [ETimesheet] VARCHAR(6) NULL,
    [MapR] VARCHAR(6) NULL,
    [RouteBuilder] VARCHAR(6) NULL,
    [MassTimesheetCheck] CHAR(1) NULL,
    [Route] VARCHAR(6) NULL,
    [CreditHold] VARCHAR(4) NULL, 
    [CreditFlag] VARCHAR(4) NULL, 
    [SalesSetup] VARCHAR(6) NULL, 
    [SalesManager] CHAR(1) NULL, 
    [PONotification] CHAR (1)        NULL,
	[ProjectModulePermission] CHAR(1) NULL, 
    [InventoryModulePermission] CHAR (1)    NULL,
	[JobCompletedPermission] CHAR (1)    NULL,
	[JobReopenPermission] CHAR (1)    NULL,
	[IsProjectManager] BIT NULL,
	[IsAssignedProject] BIT NULL,
	[LastLoginDate] DATETIME NULL,
	--[ResetPasswordEmail] Varchar(255) null,
	[LoginFailedAttempts] INT null,
    [TicketVoidPermission] INT NULL DEFAULT 0,
	[Password1]                VARCHAR (50)    NULL,
	[Password2]                VARCHAR (50)    NULL,
    [ForgotPwRequest] BIT NULL, 
    [LastUpdatePasswordDate] DATETIME NULL, 
    [PRWage] VARCHAR(6) NULL, 
    [PRDeduct] VARCHAR(6) NULL, 
    [PR] BIT NULL, 
    [ApplyUserRolePermission] SMALLINT NULL, 
    [MassPayrollTicket] VARCHAR(1) NULL, 
    [IsReCalculateLaborExpense] BIT NULL, 
	[ViolationPermission] VARCHAR(4) NULL,
    CONSTRAINT [PK_tblUser] PRIMARY KEY ([ID])
);





