CREATE TABLE [dbo].[temp1] (
    [fdate]        DATETIME        NULL,
    [fdesc]        VARCHAR (MAX)   NULL,
    [amount]       NUMERIC (30, 2) NULL,
    [stax]         INT             NULL,
    [total]        NUMERIC (30, 2) NULL,
    [taxregion]    VARCHAR (25)    NULL,
    [taxrate]      NUMERIC (30, 2) NULL,
    [taxfactor]    NUMERIC (30, 2) NULL,
    [taxable]      INT             NULL,
    [type]         INT             NULL,
    [job]          INT             NULL,
    [loc]          INT             NULL,
    [terms]        VARCHAR (10)    NULL,
    [PO]           VARCHAR (25)    NULL,
    [status]       INT             NULL,
    [batch]        INT             NULL,
    [remarks]      VARCHAR (MAX)   NULL,
    [gtax]         INT             NULL,
    [worker]       VARCHAR (75)    NULL,
    [taxregion2]   VARCHAR (50)    NULL,
    [taxrate2]     NUMERIC (30, 2) NULL,
    [billto]       VARCHAR (1000)  NULL,
    [Idate]        DATETIME        NULL,
    [fuser]        VARCHAR (10)    NULL,
    [acct]         INT             NULL,
    [chart]        INT             NULL,
    [Quan]         NUMERIC (30, 2) NULL,
    [price]        NUMERIC (30, 2) NULL,
    [Jobitem]      INT             NULL,
    [measure]      VARCHAR (10)    NULL,
    [fdescI]       VARCHAR (100)   NULL,
    [Frequency]    VARCHAR (50)    NULL,
    [Name]         VARCHAR (25)    NULL,
    [customername] VARCHAR (75)    NULL,
    [locid]        VARCHAR (50)    NULL,
    [locname]      VARCHAR (100)   NULL,
    [dworker]      VARCHAR (50)    NULL,
    [bcycle]       INT             NULL,
    [ServiceType]  VARCHAR (15)    NULL,
    [Lid]          VARCHAR (75)    NULL,
    [ContractBill] SMALLINT        NULL,
    [CustBilling]  SMALLINT        NULL
);