CREATE TABLE [dbo].[TicketDPDA_Log](
	[PK] [int] IDENTITY(1,1) NOT NULL,
	[TicketID] [int] NOT NULL,
	[Date] [datetime2](7) NULL,
	[Data] [nvarchar](max) NULL,
 CONSTRAINT [PK_TicketDPDA_Log] PRIMARY KEY CLUSTERED 
(
	[PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
