CREATE TABLE [dbo].[VioStatus](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](50) NULL,
	[Remarks] [text] NULL,
	[Count] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

