CREATE TYPE [dbo].[tblTypeRecurringInvoiceItems] AS TABLE (
   [fdate] [datetime] NULL,
	[fDesc] [varchar](max) NULL,
	[Amount] [numeric](30, 2) NULL,
	[stax] [numeric](30, 2) NULL,
	[total] [numeric](30, 2) NULL,
	[taxRegion] [varchar](25) NULL,
	[taxrate] [numeric](30, 4) NULL,
	[Taxfactor] [numeric](30, 2) NULL,
	[taxable] [numeric](30, 2) NULL,
	[type] [smallint] NULL,
	[job] [int] NULL,
	[loc] [int] NULL,
	[terms] [int] NULL,
	[PO] [varchar](25) NULL,
	[Status] [smallint] NULL,
	[Batch] [int] NULL,
	[remarks] [varchar](max) NULL,
	[gtax] [numeric](30, 2) NULL,
	[worker] [int] NULL,
	[TaxRegion2] [varchar](25) NULL,
	[Taxrate2] [numeric](30, 4) NULL,
	[BillTo] [varchar](1000) NULL,
	[Idate] [datetime] NULL,
	[Fuser] [varchar](50) NULL,
	[Acct] [int] NULL,
	[Chart] [int] NULL,
	[Quan] [numeric](30, 2) NULL,
	[Price] [numeric](30, 4) NULL,
	[Jobitem] [int] NULL,
	[measure] [varchar](15) NULL,
	[fdescI] [varchar](100) NULL,
	[Frequency] [varchar](50) NULL,
	[Name] [varchar](25) NULL,
	[customername] [varchar](75) NULL,
	[locid] [varchar](50) NULL,
	[locname] [varchar](75) NULL,
	[dworker] [varchar](50) NULL,
	[bcycle] [int] NULL,
	[ServiceType] [varchar](75) NULL,
	[lid] [varchar](75) NULL,
	[ContractBill] [smallint] NULL,
	[CustBilling] [smallint] NULL,
	[ItemDesc] [varchar](max) NULL,
	[Owner] [int] NULL,
	[JobOrg] [int] NULL,
	[DetailLevel] [int] NULL,
	[TaxType] [int] NULL,
	[GST ] [numeric](30, 4) NULL,
	[PST] [numeric](30, 4) NULL,
	[GSTRate] [numeric](30, 4) NULL,
	[DetailItem] [varchar](max) NULL);
GO

