Create  PROCEDURE [dbo].[spGetARAgingByDateDep]
	@fDate datetime,
	@DepartmentType VARCHAR(500),
	@CreditFlag TINYINT = 0
AS
BEGIN
	--SET NOCOUNT ON;
	DECLARE @text varchar(MAX)
	DECLARE @acct INT
    SET @acct=(SELECT TOP 1 ID FROM Chart WHERE DefaultNo='D1200' AND Status=0 ORDER BY ID) 
	
	SET @text= 'SELECT	t1.ID as TransID,  '
	SET @text= @text + 't1.type,(select TOP 1 Type from jobtype Where ID=i.type) as Department, '
	SET @text= @text + '(SELECT TOP 1 Name FROM   rol WHERE  ID = (SELECT TOP 1 Rol FROM   Owner WHERE  ID = l.Owner)) as cid,  '
	SET @text= @text + '(SELECT TOP 1 Name FROM   rol WHERE  ID = (SELECT TOP 1 Rol FROM   Owner WHERE  ID = l.Owner)) as CustomerName,  '
	SET @text= @text + 'l.Loc, '
	SET @text= @text + 'l.Owner, '
	SET @text= @text + 'l.ID +'' - ''+ l.Tag As LocID, '
	SET @text= @text + 'l.ID +'' - ''+ l.Tag As LocName, '
	SET @text= @text + 't1.fDate, '
	SET @text= @text + 'isnull(i.DDate, dbo.GetDueDate( t1.fDate,ISNULL(i.Terms,0))) as Due, '
	SET @text= @text + 't2.Amount as Original, '
	SET @text= @text + 't2.Balance as Total, '
	SET @text= @text + 't2.Paid as Paid, '
	SET @text= @text + 't1.fDesc, '
	SET @text= @text + 'isnull(t1.Ref,0) as Ref, '

	SET @text= @text + 'CASE WHEN isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) < 0 THEN 0 '
	SET @text= @text + 'ELSE isnull(DATEDIFF(day,isnull(i.DDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) '
	SET @text= @text + 'END '
	SET @text= @text + 'AS DueIn, '
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 0) '
	SET @text= @text + 'THEN '                  
    SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0    '                  
	SET @text= @text + 'END as CurrentDay, '
	SET @text= @text + 'CASE WHEN ((isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >= 0) or (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) < 0)) '
	SET @text= @text + 'AND (isnull(DATEDIFF(day,isnull(i.DDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 7) '
	SET @text= @text + 'THEN      '                  
    SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0 '                     
	SET @text= @text + 'END as CurrSevenDay, '               
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >= 0) AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 7) '
	SET @text= @text + 'THEN   '                     
    SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0         '             
	SET @text= @text + 'END as SevenDay,  '
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >= 0) AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 30)   '
    SET @text= @text + 'THEN  '                      
    SET @text= @text + 't2.Balance '
    SET @text= @text + 'ELSE 0          '            
	SET @text= @text + 'END as ThirtyDay,  '         
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >30) AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 60)   '
    SET @text= @text + 'THEN '                       
    SET @text= @text + 't2.Balance '
    SET @text= @text + 'ELSE 0        '              
	SET @text= @text + 'END as SixtyDay,	'            
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >= 61)  '
	SET @text= @text + 'THEN '
    SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0          '            
	SET @text= @text + 'END as SixtyOneDay,  '           
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >= 0) AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 31)   '
	SET @text= @text + 'THEN            '
	SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0          '                
	SET @text= @text + 'END as ZeroThirtyDay, '           
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >60) AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 90)   '
	SET @text= @text + 'THEN  '
	SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0       '                   
	SET @text= @text + 'END as NintyDay,      '          
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >90)  AND (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) <= 120)     '
	SET @text= @text + 'THEN           '            
	SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0    '                 
	SET @text= @text + 'END AS NintyOneDay ,'
	SET @text= @text + 'CASE WHEN (isnull(DATEDIFF(day,isnull(i.fDate, dbo.GetDueDate(t1.fDate,ISNULL(i.Terms,0))),'''+CONVERT(VARCHAR(100),@fDate)+'''),0) >120)   '
	SET @text= @text + 'THEN           '            
	SET @text= @text + 't2.Balance '
	SET @text= @text + 'ELSE 0    '                 
	SET @text= @text + 'END AS OneTwentyDay '

	SET @text= @text + 'FROM Trans AS t1 INNER JOIN  '
	SET @text= @text + '	('
	------ TRANSACTIONS PAID AND RECEIVED IN TS ------
	SET @text= @text + '	SELECT ID, Amount, Paid, (ISNULL(Amount,0)-ISNULL(Paid,0)) AS Balance, Loc  '
	SET @text= @text + '	FROM  '
	SET @text= @text + '	( '	
	SET @text= @text + '	select t.ID,t.Amount,'
	SET @text= @text + '	( 0 + (select sum(t2.Amount )*(-1) from Trans t2 where t2.Ref=t.Ref and t2.Type=99 and t2.acct='+ CONVERT(VARCHAR(50),@acct) + ' and t2.fDate<'''+CONVERT(VARCHAR(100),@fDate)+''' and t2.AcctSub=t.AcctSub group by t2.Type)) as paid,'
	SET @text= @text + '	t.AcctSub as loc from Trans t'
	SET @text= @text + '	where t.acct='+ CONVERT(VARCHAR(50),@acct) + ' and t.fDate<='''+CONVERT(VARCHAR(100),@fDate)+''' and AcctSub=t.AcctSub '
	SET @text= @text + '	and Status in ('
	SET @text= @text + '	select status from trans '
	SET @text= @text + '	where acct='+ CONVERT(VARCHAR(50),@acct) + ' and fDate<='''+CONVERT(VARCHAR(100),@fDate)+''' and AcctSub=t.AcctSub '
	SET @text= @text + '	group by trans.Status'
	SET @text= @text + '	Having sum(Amount)<>0 )  and (t.Status <>'''' )'
			
	SET @text= @text + '	union'
	SET @text= @text + '	select t.ID,t.Amount,0 as paid,t.AcctSub as loc from Trans  t'
	SET @text= @text + '	where t.acct='+ CONVERT(VARCHAR(50),@acct) + ' and t.fDate<='''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + '	and t.Status is null and t.Amount <>0 and   t.Ref not in (select Trans.Ref from Trans where Trans.acct='+ CONVERT(VARCHAR(50),@acct) + ' and Trans.type=1 and trans.AcctSub=t.AcctSub AND Trans.fDate<='''+CONVERT(VARCHAR(100),@fDate)+''')'

	SET @text= @text + '	UNION '
	SET @text= @text + '	SELECT t.ID, t.Amount, 0 AS paid, t.AcctSub AS loc'
	SET @text= @text + '	FROM Trans t left join invoice i on t.Ref=i.ref'
	SET @text= @text + '	WHERE t.acct='+ CONVERT(VARCHAR(50),@acct) + ' and t.type=1'
	SET @text= @text + '	AND t.fDate<='''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + '	AND t.Status IS NULL AND t.Amount <>0'
	SET @text= @text + '	and (SELECT count(1) FROM OpenAR WHERE TransID=t.ID)=0'

	SET @text= @text + '	) AS i  where (ISNULL(Amount, 0)-ISNULL(Paid, 0)) <>0 '

	SET @text= @text + '	UNION '

	SET @text= @text + '	SELECT ID, '
	SET @text= @text + '	ISNULL(Amount,0) AS Amount, '
	SET @text= @text + '	ISNULL((SELECT sum(isnull(Amount,0)) '
	SET @text= @text + '	FROM Trans t '
	SET @text= @text + '	INNER JOIN PaymentDetails p on t.ID = p.TransID '
	SET @text= @text + '	INNER JOIN OpenAR o ON o.Ref = p.InvoiceID AND IsInvoice = 0 '
	SET @text= @text + '	WHERE o.Type=3 AND o.TransID = Trans.ID '
	SET @text= @text + '	AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+'''),0)		 AS Paid, '
	SET @text= @text + '	(ISNULL(Amount,0) - ISNULL((SELECT sum(isnull(Amount,0)) '
	SET @text= @text + '	FROM Trans t '
	SET @text= @text + '	INNER JOIN PaymentDetails p on t.ID = p.TransID '
	SET @text= @text + '	INNER JOIN OpenAR o ON o.Ref = p.InvoiceID AND IsInvoice = 0 '
	SET @text= @text + '	WHERE o.Type=3 AND o.TransID = Trans.ID '
	SET @text= @text + '	AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+'''),0))	AS Balance, '
	SET @text= @text + '	ISNULL(AcctSub,0) AS Loc '
	SET @text= @text + '	FROM Trans '
	SET @text= @text + '	WHERE	Type IN (6,5) '
	SET @text= @text + '	AND Acct = ISNULL((SELECT TOP 1 ID FROM Chart WHERE DefaultNo=''D1200''),0) '
	SET @text= @text + '	AND fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + '	AND Amount <> 0 and (select count(1) from OpenAR where TransID=ID)>0'
	SET @text= @text + '	AND (Status = '''' or Status is null) '
	SET @text= @text + '    AND (select count(1) from OpenAR where TransID=ID) >0'
	SET @text= @text + '	UNION '
						------ RECEIVED - PAID TRANSACTIONS, INVOICE - RECEIVED PAYMENT ------
	SET @text= @text + 'SELECT			t.ID,  '
	SET @text= @text + 'ISNULL(t.Amount,0) AS Amount, ' 
	SET @text= @text + 'ISNULL((SELECT Sum(ISNULL(amount,0)) FROM Trans t  '
	SET @text= @text + 'INNER JOIN PaymentDetails p on t.ID =p.TransID  '
	SET @text= @text + 'WHERE	p.InvoiceID = i.Ref  '
	SET @text= @text + 'AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+'''  '
	SET @text= @text + 'AND ISNULL(p.IsInvoice, 1) = 1 '
	SET @text= @text + '),0) AS Paid, '
	SET @text= @text + 'ISNULL(t.Amount,0) - ISNULL((SELECT Sum(ISNULL(amount,0)) FROM Trans t  '
	SET @text= @text + 'INNER JOIN PaymentDetails p on t.ID =p.TransID  '
	SET @text= @text + 'WHERE	p.InvoiceID = i.Ref   '
	SET @text= @text + 'AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + 'AND ISNULL(p.IsInvoice, 1) = 1 '
	SET @text= @text + '),0) AS Balance, '
	SET @text= @text + 'ISNULL(AcctSub,0) AS Loc '
	SET @text= @text + 'FROM Trans t '
	SET @text= @text + 'INNER JOIN Invoice i ON i.TransID = t.ID  '
								
	SET @text= @text + 'WHERE		t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + 'AND (t.Status = '''' or  t.Status is null)  '
	SET @text= @text + 'AND t.Amount <> 0  AND t.Type NOT IN(60,61)'
	SET @text= @text + 'AND ISNULL(t.Amount,0) - ISNULL((select sum(isnull(amount,0)) from trans t  '
	SET @text= @text + 'inner join paymentdetails p on t.ID =p.TransID  '
	SET @text= @text + 'where p.InvoiceID = i.Ref and t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + 'and Isnull(p.IsInvoice, 1) = 1 '
	SET @text= @text + '),0) <> 0 '

	SET @text= @text + 'UNION '
						---- PAID TRANSACTIONS BEFORE THEY ARE RECEIVED ------
	SET @text= @text + 'SELECT			t.ID,  '
	SET @text= @text + 'ISNULL(t.Amount,0)*-1  AS Amount, '
	SET @text= @text + 'CONVERT(NUMERIC(30,2),0) as Paid, '
	SET @text= @text + 'ISNULL(t.Amount,0)*-1 AS Balance, '
	SET @text= @text + 'Invoice.Loc  '
	SET @text= @text + 'FROM			PaymentDetails p  '
	SET @text= @text + 'INNER JOIN  Trans t on t.ID = p.TransID '
	SET @text= @text + 'INNER JOIN  ReceivedPayment r on r.ID = p.ReceivedPaymentID '
	SET @text= @text + 'LEFT JOIN Invoice ON Invoice.Ref = p.InvoiceID AND ISNULL(p.IsInvoice,1) = 1 '

	SET @text= @text + 'WHERE	r.PaymentReceivedDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' and isnull(p.IsInvoice,1) =1 '
	SET @text= @text + 'AND p.InvoiceID NOT IN (SELECT Ref FROM Invoice WHERE fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''') '
	SET @text= @text + 'AND ISNULL(t.Amount,0) <> 0 '
	SET @text= @text + 'UNION '
						---- CREDIT TRANSACTIONS
			
	SET @text= @text + 'SELECT			t.ID, '
	SET @text= @text + 'ISNULL(t.Amount,0) AS Amount, '
	SET @text= @text + 'ISNULL((SELECT SUM(ISNULL(t.Amount,0)) '
	SET @text= @text + 'FROM PaymentDetails p LEFT JOIN Trans t on p.TransID = t.ID '
	SET @text= @text + 'WHERE		InvoiceID = o.Ref '
	SET @text= @text + 'AND ISNULL(IsInvoice,1) = 0 '
	SET @text= @text + 'AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''') '
	SET @text= @text + ',0) AS Paid, '
	SET @text= @text + '(ISNULL(t.Amount,0) - ISNULL((SELECT SUM(ISNULL(t.Amount,0)) '
	SET @text= @text + 'FROM PaymentDetails p LEFT JOIN Trans t on p.TransID = t.ID '
	SET @text= @text + 'WHERE		InvoiceID = o.Ref '
	SET @text= @text + 'AND ISNULL(IsInvoice,1) = 0 '
	SET @text= @text + 'AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''') '
	SET @text= @text + ',0)) AS Balance, '
	SET @text= @text + 't.AcctSub As Loc '
	SET @text= @text + 'FROM			OpenAR o '
	SET @text= @text + 'INNER JOIN  Trans t ON o.TransID = t.ID '
	SET @text= @text + 'WHERE		o.Type = 2 AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''' '
	SET @text= @text + 'AND ISNULL(t.Amount,0) - ISNULL((SELECT SUM(ISNULL(t.Amount,0)) '
	SET @text= @text + 'FROM PaymentDetails p LEFT JOIN Trans t on p.TransID = t.ID '
	SET @text= @text + 'WHERE		InvoiceID = o.Ref '
	SET @text= @text + 'AND ISNULL(IsInvoice,1) = 0 '
	SET @text= @text + 'AND t.fDate <= '''+CONVERT(VARCHAR(100),@fDate)+''') '
	SET @text= @text + ',0) <> 0 '
	SET @text= @text + 'UNION '

	SET @text= @text + 'SELECT  Trans.ID, '
	SET @text= @text + 'ISNULL(Trans.Amount,0) AS Amount, '
	SET @text= @text + '0 AS Paid, '
	SET @text= @text + 'ISNULL(Trans.Amount,0) - 0 AS Balance, '
	SET @text= @text + 'Trans.AcctSub AS Loc '

	SET @text= @text + 'FROM		Trans '
	SET @text= @text + 'WHERE	Acct = (SELECT ID FROM Chart WHERE DefaultNo = ''D1200'') '
	SET @text= @text + 'AND Type NOT IN (99, 98, 5, 6, 1, 2, 3) '
	SET @text= @text + 'AND (Status = '''' OR Status IS NULL)  AND Trans.AcctSub IS NOT NULL ' 

	SET @text= @text + 'AND Sel <> 2 '
	SET @text= @text + ') AS t2	ON t1.ID = t2.ID '
		
	SET @text= @text + ' LEFT JOIN loc l on l.Loc = t2.Loc '
	SET @text= @text + ' LEFT JOIN Rol r on r.ID = l.Owner '
	SET @text= @text + ' LEFT JOIN OpenAR o on o.Ref = t1.Ref and o.Type = 0 and t1.type = 1  and o.Loc=t2.Loc '
	SET @text= @text + ' LEFT JOIN Invoice i on i.Ref = t1.Ref and t1.type = 1 '
	SET @text= @text + ' Where i.Type IN('+@DepartmentType+') '
	SET @text= @text + ' AND (' + @CreditFlag + ' = 0 OR l.CreditFlag = 1)'
	SET @text= @text + 'ORDER BY l.ID, t1.fDate '
	


	exec(@text)
END
