CREATE PROCEDURE [dbo].[spGetRoleByID]
	@RoleID int
AS
BEGIN
	-- Get role info
	SELECT  
		RoleName
		, [Desc]
		, ISNULL([Status],0) AS Status
		, 
		isnull(Dispatch, 'NNNNNN') As Dispatch,           
		isnull(Location, 'NNNNNN') As Location,  
		isnull(PO, 'NNNN') As PO,      
		Control,          
		UserS,          
		isnull(ticket,'NNNNNN') as ticket,          
		isnull(sales,'NNNNNN') as UserSales,          
		isnull(employee,'NNNNNN') as employeeMaint,          
		isnull(tc,'NNNNNN') as TC          
		, isnull(massreview,0) as massreview
		,isnull(elevator,'NNNNNN')as elevator          
		, isnull(Chart,'NNNNNN') As Chart,          
		isnull(GLAdj,'NNNNNN')  As GLAdj,          
		isnull(CustomerPayment, 'NNNNNN') As CustomerPayment,          
		isnull(Deposit, 'NNNNNN') As Deposit,          
		isnull(Financial, 'NNNNNN') As Financial,          
		isnull(Vendor, 'NNNNNN') As Vendor,          
		isnull(Bill, 'NNNNNN') As Bill,          
		isnull(BillSelect, 'NNNNNN') As BillSelect,          
		isnull(BillPay, 'NNNNNN') As BillPay,          
		isnull(Owner, 'NNNNNN') As Owner,          
		isnull(Job, 'NNNNNN') As Job,          
		isnull(ProjectListPermission,'N') AS ProjectListPermission,          
		isnull(FinancePermission,'N') AS FinancePermission,          
		isnull(BOMPermission,'NNNN') AS BOMPermission,          
		isnull(WIPPermission,'NNNNNN') AS WIPPermission,          
		isnull(MilestonesPermission,'NNNN') AS MilestonesPermission,          
		isnull(Item, 'NNNNNN') As Item,          
		isnull(InvAdj, 'NNNNNN') As InvAdj,          
		isnull(Warehouse, 'NNNNNN') As Warehouse,          
		isnull(InvSetup, 'NNNNNN') As InvSetup,          
		isnull(InvViewer, 'NNNNNN') As InvViewer,          
		Isnull(DocumentPermission, 'NNNN') AS DocumentPermission,          
		Isnull(ContactPermission, 'NNNN') AS ContactPermission,           
		Isnull(SalesAssigned,0) as SalesAssigned,          
		Isnull(ProjecttempPermission, 'NNNN') AS ProjecttempPermission,          
		isnull(NotificationOnAddOpportunity,0) as NotificationOnAddOpportunity,        
		ISNULL(POLimit,0) AS POLimit,        
		ISNULL(POApprove,0) AS POApprove,        
		ISNULL(POApproveAmt,0) AS POApproveAmt,  
		ISNULL(MinAmount,0) AS MinAmount,  
		ISNULL(MaxAmount,0) AS MaxAmount,
		isnull(BillingCodesPermission, 'N') As BillingCodesPermission, 
		isnull(Invoice, 'NNNN') As Invoice,
		isnull(PurchasingmodulePermission, 'N')  PurchasingmodulePermission ,
		isnull(BillingmodulePermission, 'N')  BillingmodulePermission,  
		isnull(RPO, 'NNNNNN') As RPO ,
		isnull(AccountPayablemodulePermission, 'N')  AccountPayablemodulePermission,
		isnull(PaymentHistoryPermission, 'NNNN')  PaymentHistoryPermission,
		isnull(CustomermodulePermission, 'N')  CustomermodulePermission,
		isnull(Apply, 'NNNNNN') As Apply,    
		isnull(Collection, 'NNNNNN') As Collection,
		isnull(bankrec,'NNNNNN')  As bankrec,
		isnull(FinancialmodulePermission, 'N') As  FinancialmodulePermission,
		isnull(RCmodulePermission, 'N') As  RCmodulePermission,
		isnull(ProcessRCPermission, 'NNNNNN') As ProcessRCPermission,    
		isnull(ProcessC, 'NNNNNN') As ProcessC,
		isnull(ProcessT,'NNNNNN')  As ProcessT,
		isnull(RCSafteyTest,'NNNNNN')  As SafetyTestsPermission,
		isnull(RCRenewEscalatePermission, 'NNNN') AS RCRenewEscalatePermission,
		isnull(SchedulemodulePermission, 'N') AS SchedulemodulePermission,
		isnull(Resolve, 'NNNNNN') AS Resolve,
		isnull(Dispatch, 'NNNNNN') AS TicketPermission,
		isnull(MTimesheet, 'NNNNNN') AS MTimesheet,
		isnull(ETimesheet, 'NNNNNN') AS ETimesheet,
		isnull(MapR, 'NNNNNN') AS MapR,
		isnull(RouteBuilder, 'NNNNNN') AS RouteBuilder,
		isnull(MassTimesheetCheck, 'N') AS MassTimesheetCheck,
		isnull(CreditHold, 'NNNN') AS CreditHold,
		isnull(CreditFlag, 'NNNN') AS CreditFlag,
		isnull(salesmanager, 'N') AS salesmanager,
		isnull(Sales, 'NNNNNN') AS Sales,
		isnull(ToDo, 0) AS ToDo,
		isnull(ToDoC, 0) AS ToDoC,
		isnull(FU, 'NNNNNN') AS FU,
		isnull(Proposal, 'NNNNNN') AS Proposal,
		isnull(Estimates, 'NNNNNN') AS Estimates,
		isnull(AwardEstimates, 'NNNNNN') AS AwardEstimates,
		isnull(salessetup, 'NNNNNN') AS salessetup,
		isnull(PONotification, 'N') AS PONotification,
		isnull(writeOff, 'NNNNNN') AS WriteOff,
		ProjectModulePermission  ,
		InventoryModulePermission ,
		JobClose JobClosePermission ,
		JobCompletedPermission ,
		JobReopenPermission,
		isnull(IsProjectManager,0) as IsProjectManager,
		isnull(IsAssignedProject,0) as IsAssignedProject
		,isnull(TicketVoidPermission,0) as TicketVoidPermission,
		isnull(Employee, 'NNNNNN') AS Employee,  
		isnull(PRProcess, 'NNNNNN') AS PRProcess,
		isnull(PRRegister, 'NNNNNN') AS PRRegister,  
		isnull(PRReport, 'NNNNNN') AS PRReport,  
		isnull(PRWage, 'NNNNNN') AS PRWage,  
		isnull(PRDeduct, 'NNNNNN') AS PRDeduct  ,
		isnull(PR, '0') AS PR,
		isnull(Salesp, 0) AS Salesp,
		isnull(ViolationPermission,'NNNNNN')  As ViolationPermission
	FROM tblRole WHERE Id = @RoleID
	-- Get users of role
	--SELECT  
	--	u.ID as UserId
	--	, u.fUser
	--FROM tblUserRole uro INNER JOIN tblUser u on u.ID = uro.UserId WHERE uro.RoleId = @RoleID
END
