CREATE PROCEDURE [dbo].[spIsVendorExist]
	@ID INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @IsExist BIT;
	DECLARE @IsExistCD BIT;
	DECLARE @IsExistPJ BIT;
	
	SELECT @IsExistCD = CAST(CASE WHEN EXISTS(SELECT * FROM CD WHERE Vendor = @ID) THEN 1 ELSE 0 END AS BIT)
	SELECT @IsExistPJ = CAST(CASE WHEN EXISTS(SELECT * FROM PJ WHERE Vendor = @ID) THEN 1 ELSE 0 END AS BIT)

	IF(@IsExistPJ = 1 OR @IsExistCD = 1)
		BEGIN
			SET @IsExist = 1
		END
	ELSE
		BEGIN
			SET @IsExist = 0
		END
	SELECT @IsExist;
END
